---
title: "03 Transit Proximity & Trip Types"
author: "Yosephine Manihuruk"
format: html
execute:
  echo: true
  warning: false
  message: false
---

So, the idea is to categorize each trip. If both start and end points are near a bus stop, then that trip is a "sub_candidate" (which we will check later if both stops share same routes). If only the start point is near a bus stop, then it is a "last_mile" transportation. If only the end point is near a bus stop then it is a "first_mile" transportation.

```{r}
library(sf)
library(dplyr)
library(readr)
library(tidyr)
crs_proj <- 26915
```

```{r}
valid_trips <- readRDS("../Dashboard/data/valid_trips.rds")
stops_sf <- readRDS("../Dashboard/data/stops_sf.rds")
start_segments <- readRDS("../Dashboard/data/start_points.rds")
end_segments <- readRDS("../Dashboard/data/end_points.rds")
```

```{r}
start_buffered <- st_buffer(start_segments, dist = 30)
end_buffered   <- st_buffer(end_segments,   dist = 30)

start_near_raw <- st_join(
  start_buffered,
  stops_sf,
  join  = st_intersects,
  left  = TRUE
)

start_near <- start_near_raw %>%
  st_drop_geometry() %>%                 
  group_by(trip_id) %>%
  summarise(
    start_stop_ids   = list(unique(na.omit(stop_id))),
    .groups = "drop"
  ) %>%
  mutate(
    near_start_stop = lengths(start_stop_ids) > 0,
    start_stop_id   = ifelse(
      near_start_stop,
      sapply(start_stop_ids, function(x) x[1]),
      NA_character_
    )
  ) %>%
  select(trip_id, near_start_stop, start_stop_id)


end_near_raw <- st_join(
  end_buffered,
  stops_sf,
  join  = st_intersects,
  left  = TRUE
)

end_near <- end_near_raw %>%
  st_drop_geometry() %>%
  group_by(trip_id) %>%
  summarise(
    end_stop_ids   = list(unique(na.omit(stop_id))),
    .groups = "drop"
  ) %>%
  mutate(
    near_end_stop = lengths(end_stop_ids) > 0,
    end_stop_id   = ifelse(
      near_end_stop,
      sapply(end_stop_ids, function(x) x[1]),
      NA_character_
    )
  ) %>%
  select(trip_id, near_end_stop, end_stop_id)
```

```{r}
library(tmap)

set.seed(1)
sample_ids <- sample(start_segments$trip_id, 50)

sample_segments <- start_segments %>%
  filter(trip_id %in% sample_ids)

sample_buffers <- st_buffer(sample_segments, dist = 30)

plot_stops <- stops_sf

tmap_mode("view")

tm_basemap("OpenStreetMap") +
  tm_shape(sample_buffers) +
  tm_polygons(col = "lightblue", alpha = 0.4, border.col = "blue") +
  tm_shape(sample_segments) +
  tm_lines(col = "red", lwd = 2) +
  tm_shape(plot_stops) +
  tm_dots(col = "black", size = 0.05, alpha = 0.7)
```



```{r}

trip_proximity <- valid_trips %>%
  distinct(trip_id) %>%                      
  left_join(start_near, by = "trip_id") %>%
  left_join(end_near,   by = "trip_id") %>%
  mutate(
    near_start_stop = replace_na(near_start_stop, FALSE),
    near_end_stop   = replace_na(near_end_stop,   FALSE),
    trip_type = case_when(
      near_start_stop & near_end_stop  ~ "sub_candidate",
      near_start_stop & !near_end_stop ~ "last_mile",
      !near_start_stop & near_end_stop ~ "first_mile",
      TRUE                             ~ "none"
    )
  ) %>%
  select(trip_id, trip_type, near_start_stop, near_end_stop,
         start_stop_id, end_stop_id)

# sanity check
table(trip_proximity$trip_type)

saveRDS(
  trip_proximity,
  "../Dashboard/data/trip_proximity.rds",
  compress = "xz"
)
```

```{r}
percentage_trips <- trip_proximity %>%
  select(trip_id, trip_type) %>% 
  group_by(trip_id) %>%
  summarise(trip_type = first(trip_type)) %>% 
  ungroup() %>%
  count(trip_type) %>%
  mutate(percentage = n / sum(n) * 100)
  

percentage_trips
```
```{r}
object.size(trip_proximity) %>% format(units = "MB")
```

