---
title: "Minne Map thingys"
format: html
editor: visual
---

```{r}
library(ggplot2)
library(sf)
library(dplyr)
library(tigris)
library(patchwork)
library(lubridate)
library(hms)
library(readr)

# bus_routes <- sf::st_read("shp_trans_transit_routes/TransitRoutes.shp")
# scooter_index <- st_read("Motorized_Foot_Scooter_Trips_2021_-4404685251255547248.geojson")
# centerline <- sf::st_read("MPLS_Centerline//MPLS_Centerline.shp")

scooter_trips_2025 <- read_csv("Data\\scooter_trips_2025.csv")
centerline <- sf::st_read("\\Data\\MPLS_Centerline\\MPLS_Centerline.shp")


```
```{r}


valid_trips %>%
  mutate(DurationCat = cut(
    TripDuration,
    breaks = seq(0, max(TripDuration, na.rm = TRUE), by = 30),  
    include.lowest = TRUE
  )) %>%
  count(DurationCat) %>%
  arrange(desc(n))



# choose the quantile where thinning starts, e.g. 0.85
cutoff <- quantile(valid_trips$TripDuration, probs = 0.85, na.rm = TRUE)

ggplot(valid_trips, aes(TripDuration, TripDistance)) +
  geom_point() +
  geom_vline(xintercept = cutoff, color = "red", linetype = "dashed") +
  annotate("text",
           x = cutoff,
           y = max(valid_trips$TripDistance, na.rm = TRUE),
           label = paste("Cutoff =", round(cutoff, 0)),
           hjust = -0.1,
           color = "red")


```
```{r}
overlap_gap_counts$Percent <- overlap_gap_counts$n / sum(overlap_gap_counts$n) * 100

ggplot(overlap_gap_counts, aes(x = "", y = n, fill = type)) +
  geom_col(width = 1) +
  geom_text(aes(label = paste0(round(Percent, 1), "%")),
            position = position_stack(vjust = 0.5), color = "white") +
  coord_polar(theta = "y") +
  labs(title = "Trip Categories") +
  theme_void() +
  theme(legend.title = element_blank())

```

```{r}
valid_trips %>%
  filter(TripDuration <= 600) %>%
  mutate(DurationCat = cut(
    TripDuration,
    breaks = seq(0, 600, by = 60),
    include.lowest = TRUE
  )) %>%
  count(DurationCat) %>%
  ggplot(aes(x = DurationCat, y = n)) +
  geom_col()


```
```{r}
valid_trips %>%
  filter(TripDistance >= 0, TripDistance <= 3000) %>% 
  mutate(DistanceCat = cut(
    TripDistance,
    breaks = seq(0, 30000, by = 100),                  
    include.lowest = TRUE
  )) %>%
  count(DistanceCat) %>%                              
  ggplot(aes(x = DistanceCat, y = n)) +
  geom_col() +
  labs(x = "Trip distance (binned)",
       y = "Count of trips") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
```
```{r}

scooter_index <- scooter_index %>%
  filter(StartCenterlineType != 'trail' | EndCenterlineType != 'trail') %>%
  mutate(
    StartTime_clean = sub("^\\w+, ", "", StartTime),
    StartTime_clean = sub(" GMT$", "", StartTime_clean),
    EndTime_clean = sub("^\\w+, ", "", EndTime),
    EndTime_clean = sub(" GMT$", "", EndTime_clean),
    Startcleaning = as.POSIXct(StartTime_clean, format = "%d %b %Y %H:%M:%S", tz = "UTC"),
    Endcleaning = as.POSIXct(EndTime_clean, format = "%d %b %Y %H:%M:%S", tz = "UTC"),
    Start_date = as.Date(Startcleaning),
    Start_clock = as_hms(format(Startcleaning, "%H:%M:%S")),
    End_date = as.Date(Endcleaning),
    End_clock = as_hms(format(Endcleaning, "%H:%M:%S"))) %>%
  select(-StartTime_clean, -Startcleaning, -EndTime_clean, -Endcleaning)
  


```
```{r}

```
```{r}

ggplot(scooter_index, aes(x = Start_clock)) +
  geom_bar() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

heatmap_data <- scooter_cleaned_Start %>%
  group_by(STREETALL, hour(Start_clock)) %>%
  summarise(trips = n(), .groups = "drop")

ggplot(heatmap_data, aes(x = Start_clock, y = STREETALL, fill = trips)) +
  geom_tile(color = "white") +
  scale_fill_viridis_c(option = "plasma") +
  labs(
    title = "Scooter Trips by Hour and Street",
    x = "Hour of Day",
    y = "Street",
    fill = "Number of Trips"
  ) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

ggplot(data = scooter_index) +
  geom_point(aes(x = TripDuration, y = TripDistance))

ggplot(scooter_cleaned_Start) +
  geom_bar(aes( x= date))




options(tigris_use_cache = TRUE)
mpls <- places(state = "MN", year = 2020, class = "sf") |>
  filter(NAME == "Minneapolis") |>
  st_transform(4326)

scooter_cleaned_Start <- centerline %>%
  left_join(
    st_set_geometry(scooter_index, NULL),  
    by = c("GBSID" = "StartCenterlineID")
  ) %>%
  select(OBJECTID, STREETALL, GBSID, TripID, TripDuration, TripDistance, StartTime, EndTime, Start_clock, End_clock, date)

scooter_cleaned_End <- centerline %>%
  left_join(
    st_set_geometry(scooter_index, NULL),  
    by = c("GBSID" = "EndCenterlineID")
  )%>%
  select(OBJECTID, STREETALL, GBSID, TripID, TripDuration, TripDistance, StartTime, EndTime)



startLines <- ggplot() +
  geom_sf(data = mpls, fill = "gray90", color = "white", size = 0.1) +
  geom_sf(data = scooter_cleaned_Start, color = "blue", alpha = 0.01) +
  theme_minimal() +
  theme(
    axis.title = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    panel.grid = element_blank(),
    panel.border = element_blank()
  )

endLines <- ggplot() +
  geom_sf(data = mpls, fill = "gray90", color = "white", size = 0.1) +
  geom_sf(data = scooter_cleaned_End, color = "red", alpha = 0.01) +
  theme_minimal() +
  theme(
    axis.title = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    panel.grid = element_blank(),
    panel.border = element_blank()
  )

# Combine side by side
(startLines | endLines) + 
  plot_annotation(
    title = "The Starts and Ends of Commuter Bike Travel",
    theme = theme(plot.title = element_text(hjust = 0.5, size = 16, face = "bold"))
  )




```

```{r}
ggplot(data = scooter_index) %>%
  geom_point(aes(x = Trip))
```
